### basic settings
# site properties and page defaults
title: Chen Lab
subtitle: The Website of Chen Lab
description: Welcome to the Chen Lab!
logo: images/BFBF67BC-CFDF-4DBE-AA47-4BC6CABA1450.jpeg
logo-text: false
header: images/background.jpg
footer: images/background.jpg
baseurl: /Chen-lab-website

# site social media and other links
links:
  email: ruichen@bcm.edu
  google-scholar: Rui Chen
  github: your-lab
  twitter: YourLabHandle
  instagram: YourLabHandle
  youtube: YourLabChannel

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
