- id: doi:10.1186/s13059-018-1579-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-018-1579-x/MediaObjects/13059_2018_1579_Fig1_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://github.com/fe4960/GRIPT_BCM
  tags:
  - Human Genetics
  - GRIPT
  - Mendelian Disease
  - Gene Discovery

- id: doi:10.1038/s41436-020-01003-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41436-020-01003-x/MediaObjects/41436_2020_1003_Fig2_HTML.png?as=webp
  extra-links:
  tags:
  - Human Genetics
  - TLCD3B
  - Retinal Dystrophy
  
- id: doi:10.1038/s41436-020-00948-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41436-020-00948-3/MediaObjects/41436_2020_948_Fig3_HTML.png?as=webp
  extra-links:
  tags:
  - Human Genetics
  - Pathogenicity
  - Rare Variant
  - Mendelian Disease
  
- id: doi:10.1016/j.ajhg.2017.02.008
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5384039/bin/gr2.jpg
  extra-links:
  tags:
  - Human Genetics
  - CWC27
  - Retinal Degeneration

- id: doi:10.1016/j.ajhg.2016.10.008
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5142109/bin/gr2.jpg
  extra-links:
  tags:
  - Human Genetics
  - REEP6
  - Retinitis Pigmentosa
  - Retinal Dystrophy
  
- id: doi:10.1186/s13059-022-02679-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-022-02679-x/MediaObjects/13059_2022_2679_Fig1_HTML.png?as=webp
  extra-links:
    - type: preprint
      link: https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html
      text: Dataset
    - type: source
      link: https://github.com/KChen-lab/bindSC
      text: BindSC source
  tags:
  - Single Cell Omics
  - BindSC
  - Bi-CCA
  - Integration
 
