- id: doi:10.1186/s13059-018-1579-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-018-1579-x/MediaObjects/13059_2018_1579_Fig1_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://github.com/fe4960/GRIPT_BCM
  tags:
  - Human Genetics
  - GRIPT
  - Mendelian disease
  - gene discovery

- id: doi:10.1038/s41436-020-01003-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41436-020-01003-x/MediaObjects/41436_2020_1003_Fig2_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://static-content.springer.com/esm/art%3A10.1038%2Fs41436-020-01003-x/MediaObjects/41436_2020_1003_MOESM2_ESM.xlsx
  tags:
  - Human Genetics
  - TLCD3B
  - retinal dystrophy

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
